options(java.parameters = "-Xmx8000m")

library(RJDBC)




# JDBC Driver Loading from the jar file
jdbcDriver <- JDBC(driverClass="oracle.jdbc.OracleDriver", classPath="C:/Users/imart/Documents/ojdbc6.jar")
jdbcConIMBLR <- dbConnect(jdbcDriver, "jdbc:oracle:thin:@//206.191.151.214:1521/IMBL", "indiamart", "blalrtdb4iil")
##create MESHR connection to DB
#jdbcCOnMESHR <- dbConnect(jdbcDriver,"jdbc:oracle:thin:@//ora4-dl.intermesh.net/mesh","indiamart","ora926mesh)%")

start_date <- "01-JAN-2019"
end_date <- "30-APR-2019"



query <- paste0("select distinct tt.* , case when IIL_ENQ_INTEREST_MODID in ('BIGQUERY','ANDROID', 'IOS', 'WINDOWS', 'FUSIONI', 'FUSIONW', 'FUSIONA', 'FUSIONB') then 'App'
when IIL_ENQ_INTEREST_MODID in ('DIR','FCP','PRODDTL','MTDW','IM','PDFIM','STDPRD','MY','IMHOME','MDC','TDWIM') then 'Desktop' 
when IIL_ENQ_INTEREST_MODID in ('IMOB') then 'Mobile' 
end Intent_Platform
,IIL_ENQ_INTEREST_TYPE from 
(
SELECT DISTINCT A.*,
CASE WHEN iil.FK_GLUSR_USR_ID is not null and iil.FK_GL_ATTRIBUTE_ID=121 AND iil.IIL_VERIFICATION_USER_SRC_DATE IS NOT NULL THEN 'Y' ELSE 'N' end MOBILE_VERIFED

FROM
(
WITH MY_FENQ AS
(
SELECT FK_ETO_OFR_ID FENQ_OFR_ID,QUERY_MODID FENQ_MODID , ENQUIRY_SMS_ID FROM ETO_OFR_FROM_FENQ WHERE TRUNC(DATE_R) BETWEEN", "'", start_date, "'" ," AND ", "'", end_date, "'","
AND FK_ETO_OFR_ID IS NOT NULL
UNION
SELECT FK_ETO_OFR_ID, QUERY_MODID, ENQUIRY_SMS_ID FROM ETO_OFR_FROM_FENQ_ARCH WHERE TRUNC(DATE_R) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'","
AND FK_ETO_OFR_ID IS NOT NULL
)
, MY_OFFERS AS 
( 
SELECT DIR_QUERY_MCATID, QUERY_MODID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,QUERY_REFERENCE_URL REF_URL, 2 AS STATUS, null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG ,RAG_SCORE_TOTAL,SENDERNAME SENDER_NAME ,S_MOBILE MOBILE ,S_CITY CITY ,TRUNC(DATE_R) DATE_R,
DECODE(DIR_QUERY_FREE_BL_TYP,2,'FENQ','DIRECT') BL_TYPE, 0 EXPIRED_FLAG FROM DIR_QUERY_FREE --gen
WHERE TRUNC(DATE_R) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'","
UNION 
SELECT FK_GLCAT_MCAT_ID, FK_GL_MODULE_ID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,ETO_OFR_PAGE_REFERRER REF_URL,1,null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG, RAG_SCORE_TOTAL,ETO_OFR_S_SENDERNAME SENDER_NAME,ETO_OFR_S_PH_MOBILE MOBILE,ETO_OFR_S_CITY CITY, TRUNC(ETO_OFR_POSTDATE_ORIG),
DECODE(FK_GL_MODULE_ID,'FENQ','FENQ','DIRECT'), 0 EXPIRED_FLAG FROM ETO_OFR 
WHERE TRUNC(ETO_OFR_POSTDATE_ORIG) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," --gen
UNION 
SELECT FK_GLCAT_MCAT_ID, FK_GL_MODULE_ID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,ETO_OFR_PAGE_REFERRER REF_URL,1,null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG, RAG_SCORE_TOTAL,ETO_OFR_S_SENDERNAME SENDER_NAME,ETO_OFR_S_PH_MOBILE MOBILE,ETO_OFR_S_CITY CITY,TRUNC(ETO_OFR_POSTDATE_ORIG),
DECODE(FK_GL_MODULE_ID,'FENQ','FENQ','DIRECT'), 1 EXPIRED_FLAG
FROM ETO_OFR_EXPIRED WHERE TRUNC(ETO_OFR_POSTDATE_ORIG) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," 
AND ETO_OFR_APPROV = 'A'--approved
UNION 
SELECT FK_GLCAT_MCAT_ID, FK_GL_MODULE_ID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,ETO_OFR_PAGE_REFERRER REF_URL,1,null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG, RAG_SCORE_TOTAL,ETO_OFR_S_SENDERNAME SENDER_NAME,ETO_OFR_S_PH_MOBILE MOBILE,ETO_OFR_S_CITY CITY,TRUNC(ETO_OFR_POSTDATE_ORIG),
DECODE(FK_GL_MODULE_ID,'FENQ','FENQ','DIRECT'), 0 EXPIRED_FLAG
FROM ETO_OFR_EXPIRED WHERE TRUNC(ETO_OFR_POSTDATE_ORIG) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'","
AND ETO_OFR_APPROV <> 'A' --gen
UNION 
SELECT FK_GLCAT_MCAT_ID, FK_GL_MODULE_ID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,ETO_OFR_PAGE_REFERRER REF_URL,1,null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG, RAG_SCORE_TOTAL,ETO_OFR_S_SENDERNAME SENDER_NAME,ETO_OFR_S_PH_MOBILE MOBILE,ETO_OFR_S_CITY CITY,TRUNC(ETO_OFR_POSTDATE_ORIG),
DECODE(FK_GL_MODULE_ID,'FENQ','FENQ','DIRECT'), 1 EXPIRED_FLAG 
FROM ETO_OFR_EXPIRED_ARCH WHERE TRUNC(ETO_OFR_POSTDATE_ORIG) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," 
AND ETO_OFR_APPROV = 'A'--approved
UNION 
SELECT FK_GLCAT_MCAT_ID, FK_GL_MODULE_ID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,ETO_OFR_PAGE_REFERRER REF_URL,1,null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG, RAG_SCORE_TOTAL,ETO_OFR_S_SENDERNAME SENDER_NAME,ETO_OFR_S_PH_MOBILE MOBILE,ETO_OFR_S_CITY CITY,TRUNC(ETO_OFR_POSTDATE_ORIG),
DECODE(FK_GL_MODULE_ID,'FENQ','FENQ','DIRECT') , 0 EXPIRED_FLAG
FROM ETO_OFR_EXPIRED_ARCH WHERE TRUNC(ETO_OFR_POSTDATE_ORIG) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," 
AND ETO_OFR_APPROV <> 'A' --gen
UNION 
SELECT FK_GLCAT_MCAT_ID, FK_GL_MODULE_ID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,ETO_OFR_PAGE_REFERRER REF_URL,3,null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG ,RAG_SCORE_TOTAL,ETO_OFR_S_SENDERNAME SENDER_NAME,ETO_OFR_S_PH_MOBILE MOBILE,ETO_OFR_S_CITY CITY,TRUNC(ETO_OFR_POSTDATE_ORIG) ,
'DIRECT', 0 EXPIRED_FLAG 
FROM ETO_OFR_TEMP_DEL WHERE TRUNC(ETO_OFR_POSTDATE_ORIG) 
BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," --gen
UNION 
SELECT FK_GLCAT_MCAT_ID, FK_GL_MODULE_ID MODID,ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,ETO_OFR_PAGE_REFERRER REF_URL,3, null as ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG ,RAG_SCORE_TOTAL,ETO_OFR_S_SENDERNAME SENDER_NAME,ETO_OFR_S_PH_MOBILE MOBILE,ETO_OFR_S_CITY CITY,TRUNC(ETO_OFR_POSTDATE_ORIG),
'DIRECT', 0 EXPIRED_FLAG 
FROM ETO_OFR_TEMP_DEL_ARCH --gen
WHERE TRUNC(ETO_OFR_POSTDATE_ORIG) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," 
UNION
SELECT DIR_QUERY_MCATID, QUERY_MODID MODID,DIR_QUERY_FREE_REFID ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,QUERY_REFERENCE_URL REF_URL, 3 AS STATUS,ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG ,RAG_SCORE_TOTAL,SENDERNAME SENDER_NAME ,S_MOBILE MOBILE ,S_CITY CITY,TRUNC(DATE_R),
'FENQ', 0 EXPIRED_FLAG 
FROM ETO_OFR_FROM_FENQ--gen
WHERE TRUNC(DATE_R) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," AND FK_ETO_OFR_ID IS NULL
UNION
SELECT DIR_QUERY_MCATID, QUERY_MODID MODID,DIR_QUERY_FREE_REFID ETO_OFR_DISPLAY_ID,FK_GLUSR_USR_ID,QUERY_REFERENCE_URL REF_URL, 3 AS STATUS,ENQUIRY_SMS_ID,
USER_IDENTIFIER_FLAG ,RAG_SCORE_TOTAL,SENDERNAME SENDER_NAME ,S_MOBILE MOBILE ,S_CITY CITY,TRUNC(DATE_R),
'FENQ', 0 EXPIRED_FLAG
FROM ETO_OFR_FROM_FENQ_ARCH--gen
WHERE TRUNC(DATE_R) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," AND FK_ETO_OFR_ID IS NULL
)

SELECT 
DIR_QUERY_MCATID, TRUNC(DATE_R),
--ETO_OFR_DISPLAY_ID,
COUNT( ETO_OFR_DISPLAY_ID) GENERATED_BL, 
COUNT( DECODE( STATUS, 1, ETO_OFR_DISPLAY_ID, NULL ) ) APPROVED_BL, 
COUNT( DISTINCT DECODE(SOLD_TRANSACTION,0,NULL,ETO_OFR_DISPLAY_ID )) SOLD_TOTAL, 
SUM( SOLD_TRANSACTION ) TRANS_TOTAL,
CASE WHEN USER_IDENTIFIER_FLAG =67 THEN 'enquiry intent'
WHEN USER_IDENTIFIER_FLAG = 68 THEN 'search intent'
WHEN USER_IDENTIFIER_FLAG = 69 THEN 'email-intent' 
WHEN USER_IDENTIFIER_FLAG = 65 THEN 'bl-form intent'
WHEN USER_IDENTIFIER_FLAG = 64 THEN 'call intent' 
WHEN USER_IDENTIFIER_FLAG = 66 THEN 'browse intent' 
WHEN USER_IDENTIFIER_FLAG = 63 THEN 'single-click enquiry intent'
WHEN USER_IDENTIFIER_FLAG = 62 THEN 'PNS Intent' 
WHEN USER_IDENTIFIER_FLAG = 70 THEN 'PNS Remarketing' 
WHEN USER_IDENTIFIER_FLAG = 71 THEN 'single-click bl intent'
WHEN USER_IDENTIFIER_FLAG = 72 THEN 'Call Feedback Intent' END INTENT_TYPE,
CASE WHEN USER_IDENTIFIER_FLAG IN (2,3,5,6,7,8,9,10,13,14,15,16,19,21,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99) THEN 'DNC'
WHEN USER_IDENTIFIER_FLAG IN (0,1,20,24,26,27,28,11,12,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59) THEN 'MUST_CALL'
WHEN USER_IDENTIFIER_FLAG IN (17,18,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79) THEN 'INTENT_POOL' END BL_POOL,
CASE when MODID = 'IMOB' THEN 'MOB_GEN'
WHEN MODID IN ('ANDROID', 'IOS', 'WINDOWS', 'FUSIONI', 'FUSIONW', 'FUSIONA', 'FUSIONB') THEN 'APPS_GEN' 
WHEN MODID IN ('DIR','FCP','PRODDTL','MTDW','IM','PDFIM','STDPRD','MY','IMHOME','MDC','TDWIM') THEN 'DESKTOP' END PLATFORM,
CASE WHEN RAG_SCORE_TOTAL =1 THEN 'RED'
WHEN RAG_SCORE_TOTAL=2 THEN 'AMBER'
WHEN RAG_SCORE_TOTAL=3 THEN 'GREEN' END RAG_SCORE,
FK_GLUSR_USR_ID,
--,SENDER_NAME , MOBILE ,
CITY ,
COUNT(CASE WHEN (SENDER_NAME IS NOT NULL OR GLUSR_USR_FIRSTNAME IS NOT NULL) THEN ETO_OFR_DISPLAY_ID END) BL_CNT_WITH_NAME , 
COUNT(CASE WHEN (MOBILE IS NOT NULL OR GLUSR_USR_PH_MOBILE IS NOT NULL) THEN ETO_OFR_DISPLAY_ID END) BL_CNT_WITH_MOBILE , 
COUNT(CASE WHEN (CITY IS NOT NULL OR GLUSR_USR_CITY IS NOT NULL) THEN ETO_OFR_DISPLAY_ID END) BL_CNT_WITH_CITY ,ENQUIRY_SMS_ID 
FROM
( 
SELECT ETO_OFR_DISPLAY_ID, DIR_QUERY_MCATID, MODID, FK_GLUSR_USR_ID, STATUS, SOLD_TRANSACTION, BL_TYPE ,RAG_SCORE_TOTAL,USER_IDENTIFIER_FLAG,SENDER_NAME , MOBILE , CITY ,
EXPIRED_FLAG,GLUSR_USR_FIRSTNAME,GLUSR_USR_PH_MOBILE,GLUSR_USR_CITY, nvl(ENQUIRY_SMS_ID,ENQUIRY_SMS ) ENQUIRY_SMS_ID,DATE_R
FROM
( 
SELECT MY_OFFERS.ETO_OFR_DISPLAY_ID, DIR_QUERY_MCATID, NVL(FENQ_MODID,MODID) MODID,MY_OFFERS.ENQUIRY_SMS_ID,MY_fenq.ENQUIRY_SMS_ID ENQUIRY_SMS,my_offers.DATE_R,
--NVL( CASE WHEN FENQ_MODID='INTENT' THEN IIL_ENQ_INTEREST_MODID ELSE FENQ_MODID END ,MY_OFFERS.MODID) MODID, 
MY_OFFERS.FK_GLUSR_USR_ID, STATUS, MY_OFFERS.USER_IDENTIFIER_FLAG,MY_OFFERS.RAG_SCORE_TOTAL,
COUNT(DISTINCT ETO_LEAD_PUR_ID) SOLD_TRANSACTION , BL_TYPE, EXPIRED_FLAG,GLUSR_USR.GLUSR_USR_FIRSTNAME,
GLUSR_USR.GLUSR_USR_PH_MOBILE,GLUSR_USR.GLUSR_USR_CITY,
SENDER_NAME , MOBILE , CITY 
FROM MY_OFFERS, ETO_ATTRIBUTE , ETO_LEAD_PUR_HIST , MY_FENQ,GLUSR_USR 
WHERE MY_OFFERS.ETO_OFR_DISPLAY_ID = FK_ETO_OFR_DISPLAY_ID 
AND MY_OFFERS.ETO_OFR_DISPLAY_ID = FK_ETO_OFR_ID 
AND MY_OFFERS.ETO_OFR_DISPLAY_ID = FENQ_OFR_ID
AND MY_OFFERS.FK_GLUSR_USR_ID = GLUSR_USR_ID
GROUP BY MY_OFFERS.ETO_OFR_DISPLAY_ID, DIR_QUERY_MCATID, NVL(FENQ_MODID,MODID),MY_OFFERS.ENQUIRY_SMS_ID,MY_fenq.ENQUIRY_SMS_Id,my_offers.DATE_R,
--NVL( CASE WHEN FENQ_MODID='INTENT' THEN IIL_ENQ_INTEREST_MODID ELSE FENQ_MODID END ,MY_OFFERS.MODID), 
MY_OFFERS.FK_GLUSR_USR_ID, STATUS , BL_TYPE, EXPIRED_FLAG,MY_OFFERS.USER_IDENTIFIER_FLAG,MY_OFFERS.RAG_SCORE_TOTAL,
SENDER_NAME , MOBILE , CITY ,GLUSR_USR.GLUSR_USR_FIRSTNAME,GLUSR_USR.GLUSR_USR_PH_MOBILE,GLUSR_USR.GLUSR_USR_CITY
) 
) 
--where DIR_QUERY_MCATID =178569 
GROUP BY DIR_QUERY_MCATID, USER_IDENTIFIER_FLAG,MODID,RAG_SCORE_TOTAL,FK_GLUSR_USR_ID,
SENDER_NAME , MOBILE , CITY ,status,ENQUIRY_SMS_ID,TRUNC(DATE_R)
--,ETO_OFR_DISPLAY_ID
)A JOIN
(select DISTINCT FK_GL_ATTRIBUTE_ID, IIL_VERIFICATION_USER_SRC_DATE , FK_GLUSR_USR_ID FROM IIL_VERIFICATION_DETAILS
where FK_GL_ATTRIBUTE_ID=121
--FK_GL_ATTRIBUTE_ID=121 AND IIL_VERIFICATION_USER_SRC_DATE IS NOT NULL
--GROUP BY FK_GL_ATTRIBUTE_ID, IIL_VERIFICATION_USER_SRC_DATE 
) IIL
ON A.FK_GLUSR_USR_ID = IIL.FK_GLUSR_USR_ID 
) tt left outer join 
(
SELECT IIL_ENQ_INTEREST_MODID,IIL_ENQ_INTEREST_FENQ_ID,IIL_ENQ_INTEREST_TYPE FROM IIL_ENQUIRY_INTEREST where
TRUNC(IIL_ENQ_INTEREST_DATE) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'"," 
UNION
SELECT IIL_ENQ_INTEREST_MODID,IIL_ENQ_INTEREST_FENQ_ID,IIL_ENQ_INTEREST_TYPE FROM IIL_ENQUIRY_INTEREST_ARCH where
TRUNC(IIL_ENQ_INTEREST_DATE) BETWEEN ", "'", start_date, "'" ," AND ", "'", end_date, "'","

) IIL_INT
on tt.ENQUIRY_SMS_ID = IIL_INT.IIL_ENQ_INTEREST_FENQ_ID")



queryresult <- dbGetQuery(jdbcConIMBLR,query)

write.csv(queryresult, "My_data.csv", row.names = F, quote = T)
